#!/bin/sh
# Reboot the device.

. /etc/alphasound/session.sh
. /etc/alphasound/reply.sh
require_session

[ "$REQUEST_METHOD" = "POST" ] || reply "405 Method Not Allowed" "use POST"

reply_and_reboot "rebooting…"
