// Shairport Sync configuration for Alphasound
// Runtime values are applied from /media/mmcblk0p1/alphasound.txt on each boot

general =
{
    name = "Alphasound";
    ignore_volume_control = "yes";
    volume_max_db = -3.00;
};

alsa =
{
    output_device = "hw:0";
};
